version: '3'
services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - manager
      - gateway
  gateway:
    build: ./gateway
    container_name: gateway
    expose:
      - "80"
    depends_on:
      - transfer
      - account
  manager:
    build: ./manager
    container_name: manager
    expose:
      - "80"
  account:
    build: ./account
    container_name: account
    expose:
      - "80"
  transfer:
    build: ./transfer
    container_name: transfer
    expose:
      - "80"
    ports:
      - 5000:80
